server:
  port: 80
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
google:
  url: ${GOOGLE_API_URL}
  apikey: ${GOOGLE_MAP_TOKEN}